package org.omg.CORBA;

/**
* org/omg/CORBA/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Tuesday, 21 February, 2023 9:31:14 AM EST
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (org.omg.CORBA.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.AdminHelper.type ();
  }

}
