package org.omg.CORBA;


/**
* org/omg/CORBA/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Tuesday, 21 February, 2023 9:31:14 AM EST
*/

public interface AdminOperations 
{
  String addMovieSlots (String movieID, String movieName, int bookingCapacity);
  String removeMovieSlots (String movieID, String movieName);
  String listMovieShowsAvailability (String movieName);
} // interface AdminOperations
