package org.omg.CORBA;


/**
* org/omg/CORBA/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Tuesday, 21 February, 2023 9:31:14 AM EST
*/

public interface Admin extends AdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Admin
