package org.omg.CORBA;


/**
* org/omg/CORBA/CustomerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Tuesday, 21 February, 2023 9:31:14 AM EST
*/

public interface CustomerOperations 
{
  String exchangeTickets (String customerID, String oldMovieName, String movieID, String newMovieID, String newMovieName, int numberOfTickets);
  String bookMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String getBookingSchedule (String customerID);
  String cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
} // interface CustomerOperations
