package org.omg.CORBA;

/**
* org/omg/CORBA/CustomerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Tuesday, 21 February, 2023 9:31:14 AM EST
*/

public final class CustomerHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.Customer value = null;

  public CustomerHolder ()
  {
  }

  public CustomerHolder (org.omg.CORBA.Customer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.CustomerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.CustomerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.CustomerHelper.type ();
  }

}
