package org.omg.CORBA;


/**
* org/omg/CORBA/CustomerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Tuesday, 21 February, 2023 9:31:14 AM EST
*/

public abstract class CustomerPOA extends org.omg.PortableServer.Servant
 implements org.omg.CORBA.CustomerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("exchangeTickets", new java.lang.Integer (0));
    _methods.put ("bookMovieTickets", new java.lang.Integer (1));
    _methods.put ("getBookingSchedule", new java.lang.Integer (2));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/omg/CORBA/Customer/exchangeTickets
       {
         String customerID = in.read_wstring ();
         String oldMovieName = in.read_wstring ();
         String movieID = in.read_wstring ();
         String newMovieID = in.read_wstring ();
         String newMovieName = in.read_wstring ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, oldMovieName, movieID, newMovieID, newMovieName, numberOfTickets);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 1:  // org/omg/CORBA/Customer/bookMovieTickets
       {
         String customerID = in.read_wstring ();
         String movieID = in.read_wstring ();
         String movieName = in.read_wstring ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // org/omg/CORBA/Customer/getBookingSchedule
       {
         String customerID = in.read_wstring ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 3:  // org/omg/CORBA/Customer/cancelMovieTickets
       {
         String customerID = in.read_wstring ();
         String movieID = in.read_wstring ();
         String movieName = in.read_wstring ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBA/Customer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Customer _this() 
  {
    return CustomerHelper.narrow(
    super._this_object());
  }

  public Customer _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerPOA
